spring:
  config:
    import: "optional:application-prod-environment.properties"
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_SENDER}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

application:
  email:
    receiver: ${MAIL_RECEIVER}
    sender: ${MAIL_SENDER}