mongo_url=mongodb://localhost:27017
mongo.database=miloverada

postgres_username=postgres
postgres_password=admin
postgres_url=jdbc:postgresql://localhost:5432/postgres

port=6060
ssl.enabled=false

MAIL=application.miloverada@gmail.com
MAIL_PASSWORD=esfg wlli gotw wils